#ifndef PREDICTIONTABLE_GRAMMAR_H
#define PREDICTIONTABLE_GRAMMAR_H

#define CARACTER_VAZIO 'e'
#define CARACTER_VAZIO_STRING "e"
#define CARACTER_FINAL_ARQUIVO '$'
#define TAMANHO_MAXIMO_DA_REGRA 500

#endif //PREDICTIONTABLE_GRAMMAR_H
